name: Mend Unified Agent Scan + Policy Check for Default Branch

on:
  push:
    branches:
      - master
      - main
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
# Replace lines 14-6 with your relevant build steps
    - uses: actions/setup-node@v3
      with:
        node-version: 14

    - name: Mend Unified Agent Scan
      env:
        WS_APIKEY: ${{secrets.APIKEY}}
        WS_USERKEY: ${{secrets.USERKEY}}
        WS_WSS_URL: https://saas.mend.io/agent
        WS_PRODUCTNAME: ${{github.event.repository.name}}
        WS_PROJECTNAME: ${{github.event.repository.name}}_${{github.ref_name}}
        WS_CHECKPOLICIES: TRUE
      run: |
        echo Downloading Mend Unified Agent
        curl -LJO https://unified-agent.s3.amazonaws.com/wss-unified-agent.jar
        if [[ "$(curl -sL https://unified-agent.s3.amazonaws.com/wss-unified-agent.jar.sha256)" != "$(sha256sum wss-unified-agent.jar)" ]] ; then
          echo "Integrity Check Failed"
        else
          echo "Integrity Check Passed"
          echo Starting Mend Scan
          java -jar wss-unified-agent.jar
        fi
    - name: 'Upload WhiteSource folder'
      uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: WhiteSource
        path: whitesource
        retention-days: 1
        