# ******** Mend Unified CLI Template for Gitlab CI ********
#
# You may wish to alter this file to override the build tool and Mend scanning technologies.
# Note: This example used a self-hosted Gitlab-runner running with Shell executor as described here: https://docs.gitlab.com/ee/ci/docker/using_docker_build.html#use-the-shell-executor
#
# For more configuration options, please check the technical documentation portal:
# 📚 https://docs.mend.io/bundle/integrations/page/scan_with_the_mend_cli.html
#
# ******** Description ********
# mend image will automatically scan an image for vulnerabilities with Operating System packages, Open Source vulnerabilities, and for secrets.

# If you are NOT using a service user, and have multiple organizations, don't forget to set the organization in the scope parameter
# The following values should be added as environment variables with email and userKey being secrets
#    MEND_URL: the mend url that you login to - (https://saas.mend.io) for example
#    MEND_EMAIL: the user email for the mend platform account you wish to scan with
#    MEND_USER_KEY: the user key found under my profile for the user you wish to scan with


stages:
  - scan

mend-image-scan:
  stage: scan
  variables:
    IMAGE_TAG: $CI_JOB_ID
    IMAGE_NAME: REPO_NAME/IMAGE_NAME
    MEND_EMAIL: $MEND_EMAIL
    MEND_USER_KEY: $MEND_USER_KEY
    MEND_URL: "https://saas.mend.io"
    #   MEND_URL: "https://saas-eu.mend.io"
  

  before_script:
    - docker info

  script: |
    docker build -t $IMAGE_NAME:$IMAGE_TAG . -f Dockerfile
    echo Downloading Mend CLI
    curl https://downloads.mend.io/cli/linux_amd64/mend -o ./mend && chmod +x ./mend
    echo Run Mend Image scan
    ./mend image $IMAGE_NAME:$IMAGE_TAG  --local-pull
    cp -r ~/.mend/logs $CI_PROJECT_DIR/mend-logs
  artifacts:
    paths:
      - mend-logs/
    when: always