version: "2"
services:

  remediate-server:
    image: wss-remediate:latest
    container_name: remediate-server
    environment:
      LOG_LEVEL: DEBUG
      POETRY_REPOSITORIES_MAIN_URL: "https://<artifactory_instance>.jfrog.io/artifactory/api/pypi/simple"
      POETRY_HTTP_BASIC_MAIN_USERNAME: "<username>" # Can be an email address that is not urlencoded
      POETRY_HTTP_BASIC_MAIN_PASSWORD: "<password>"
    ports:
      - "8080:8080"
    volumes:
      - "/path/to/prop.json:/etc/usr/local/whitesource/conf/prop.json"
      - "/path/to/config.js:/usr/src/app/config.js"
    restart: always
    extra_hosts:
      - "files.pythonhosted.org:127.0.0.1"
      - "pypi.org:127.0.0.1"
    logging:
      driver: local
      options:
        max-size: 1m
        max-file: "5"

  app:
    image: wss-ghe-app:latest
    container_name: wss-ghe-app
    environment:
      LOG_LEVEL: DEBUG
    ports:
      - "9494:9494"
      - "5678:5678"
    volumes:
      - "/path/to/prop.json:/etc/usr/local/whitesource/conf/prop.json"
    logging:
      driver: local
      options:
        max-size: 1m
        max-file: "5"


  scanner:
    image: wss-scanner:latest
    container_name: wss-scanner-ghe
    environment:
      EXTERNAL_LOG_IN_CONSOLE: "true"
      LOG_LEVEL: DEBUG
      POETRY_REPOSITORIES_MAIN_URL: "https://<artifactory_instance>.jfrog.io/artifactory/api/pypi/simple"
      POETRY_HTTP_BASIC_MAIN_USERNAME: "<username>"
      POETRY_HTTP_BASIC_MAIN_PASSWORD: "<password>"
    extra_hosts:
      - "files.pythonhosted.org:127.0.0.1"
      - "pypi.org:127.0.0.1"
    ports:
      - "9393:9393"
    volumes:
      - "/path/to/prop.json:/etc/usr/local/whitesource/conf/prop.json"
    restart: always
    depends_on:
      - app
    logging:
      driver: local
      options:
        max-size: 1m
        max-file: "5"


networks:
  default:
    name: my_bridge
    external: false
