# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:
  example-mend-job:
    docker:
      - image: circleci/openjdk:8u171-jdk
    working_directory: ~/repo
    environment:
      MAVEN_OPTS: -Xmx3200m
    steps:
      - checkout
      - run:
          name: maven install
          command: mvn clean install
      # The Unified Agent scan should be called AFTER a package manager build step such as "mvn clean install -DskipTests=true" or "npm install --only=prod"
      # Execute Mend scan, curling the latest unified agent. Remeber to set environment variables (api key, url, project name and product name, they need to be upper case too)
      # WS_APIKEY
      # WS_USERKEY
      # WS_WSS_URL
      # WS_PRODUCTNAME
      # WS_PROJECTNAME
      - run: 
          name: Download Mend
          command: bash <(curl -LJO https://unified-agent.s3.amazonaws.com/wss-unified-agent.jar)
      - run:
          name: Run Mend
          command: java -jar wss-unified-agent.jar
workflows:
  example-workflow:
    jobs:
      - example-mend-job