name: Mend ws-conan-scanner Release Scan

on:
  push:
    branches:
      - '**release**'

jobs:
  mendscan:
    env:
        WS_APIKEY: ${{secrets.PROD_APIKEY}}
        WS_USERKEY: ${{secrets.PROD_USERKEY}}
        WS_WSS_URL: https://saas.mend.io/agent


    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Conan
      run: |
        python -m pip install --upgrade pip
        pip install virtualenv --user
        sudo apt install -y cmake
        pip install conan --upgrade
        conan profile new default --detect
        conan profile update settings.compiler.libcxx=libstdc++11 default
    - name: Build 
      run: |
        mkdir build && cd build
        conan install ..
        cmake .. -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release
        cmake --build .
    - name: ws-conan-scanner
      env:
        WS_PRODUCTNAME: ${{github.event.repository.name}}
        WS_PROJECTNAME: ${{github.event.repository.name}}_${{github.ref_name}}
        WS_EXCLUDES: "**/*conan_export.tgz **/*conan_package.tgz **/*conanfile.py **/node_modules **/src/test **/testdata **/*sources.jar **/*javadoc.jar"
      run: |
        echo Downloading Mend Unified Agent
        curl -LJO https://unified-agent.s3.amazonaws.com/wss-unified-agent.jar
        if [[ "$(curl -sL https://unified-agent.s3.amazonaws.com/wss-unified-agent.jar.sha256)" != "$(sha256sum wss-unified-agent.jar)" ]] ; then
          echo "Integrity Check Failed"
        else
          echo "Integrity Check Passed"
          echo "Starting ws-conan-scanner install"
          pip install ws-conan-scanner
          export WS_URL=$(echo $WS_WSS_URL | awk -F "/agent" '{print $1}')
          ws_conan_scanner  -a $PWD -d $PWD -u $WS_URL -k $WS_USERKEY -t $WS_APIKEY --productName $WS_PRODUCTNAME --projectName $WS_PROJECTNAME
        fi