version: "3"
services:

  remediate:
    image: wss-remediate:latest
    container_name: remediate-server
    environment:
      LOG_LEVEL: "DEBUG"
      DOCKER_REGISTRY: "https://<artifactory_instance>.jfrog.io"
      DOCKER_USER: "<username>"
      DOCKER_PASS: "<password>"
    ports:
      - "8083:8080"
    volumes:
      - "/path/to/prop.json:/etc/usr/local/whitesource/conf/prop.json"
      - "/path/to/config.js:/usr/src/app/config.js"
    restart: always
    extra_hosts:
      - "index.docker.io:127.0.0.1"
      - "auth.docker.io:127.0.0.1"
    logging:
      driver: local
      options:
        max-size: 1m
        max-file: "5"


  app:
    build:
      context: wss-ghe-app/docker
      dockerfile: Dockerfile
    image: wss-ghe-app:{app-version}
    container_name: wss-ghe-app
    environment:
      LOG_LEVEL: "DEBUG"
    ports:
      - "9494:9494"
      - "5678:5678"
    volumes:
      - "/path/to/prop.json:/etc/usr/local/whitesource/conf/prop.json"
    restart: always
    depends_on:
      - remediate
    logging:
      driver: local
      options:
        max-size: 1m
        max-file: "5"


  scanner:
    build:
      context: wss-scanner/docker
      dockerfile: Dockerfilefull
    image: wss-scanner:{scanner-version}
    container_name: wss-scanner-ghe
    env_file:
      - "~/ghe-config/package-settings.env"
    environment:
      EXTERNAL_LOG_IN_CONSOLE: "true"
      LOG_LEVEL: "DEBUG"
    ports:
      - "9393:9393"
      - "4000:4000"
    volumes:
      - "/path/to/prop.json:/etc/usr/local/whitesource/conf/prop.json"
    restart: always
    depends_on:
      - app
    logging:
      driver: local
      options:
        max-size: 1m
        max-file: "5"


networks:
  default:
    name: my_bridge
    external: false
