name: 'mend-cli-scan'

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    echo Downloading Mend CLI
    curl https://downloads.mend.io/production/unified/latest/linux_amd64/mend -o /usr/local/bin/mend && chmod +x /usr/local/bin/mend
    echo Start Mend Container scan
    mend image ubuntu:22.10
  env:
    MEND_EMAIL: $(MEND_EMAIL)
    MEND_USER_KEY: $(MEND_USERKEY)
    MEND_URL: https://saas.mend.io
    MEND_ORG_UUID: $(MEND_SCA_ORG)
  displayName: 'Mend Container Scan'
