default:
  image: maven:3.8.4-openjdk-17

stages:
  - scan

mend_cli_scan:
  stage: scan
  variables:
    #SCA
    MEND_EMAIL: $MEND_SCA_EMAIL
    MEND_USER_KEY: $MEND_SCA_USERKEY
    MEND_URL: "https://saas.mend.io"
    #SAST
    MEND_SAST_SERVER_URL: "https://saas-eu.mend.io/sast"
    MEND_SAST_API_TOKEN: $MEND_SAST_API
    MEND_SAST_ORGANIZATION: $MEND_SAST_ORGANIZATION

  script:
    # Add your package manager build here
    # - mvn clean install -DskipTests
    - echo Downloading Mend CLI
    - curl -LJO https://downloads.mend.io/production/unified/latest/linux_amd64/mend && chmod +x mend
    - echo Start Mend CLI scan
    - ./mend sca
    - ./mend sast
