# The user needs to set up enviroment variables in Bitbucket CI, see here for more inforamtion: https://support.atlassian.com/bitbucket-cloud/docs/variables-and-secrets/
# The environment variables are:
# MEND_EMAIL: MEND_SCA_EMAIL
# MEND_USER_KEY: MEND_SCA_USERKEY
# MEND_URL: https://saas.mend.io

image: atlassian/default-image:latest
  
pipelines:
  default:
  # Build steps
    - step:
        name: NPM Build
        caches:
          - node
        script:
          - npm install
  # Mend CLI
    - step:
        name: Mend SCA Scan
        script: 
        - |
          echo "Downloading Mend CLI"
          curl https://downloads.mend.io/production/unified/latest/linux_amd64/mend -o /usr/local/bin/mend && chmod +x /usr/local/bin/mend
          echo "Mend Container Scan"
          mend image ubuntu:22.10